src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="article")
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publish_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $update_at;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", orphanRemoval=true)
     */
    private $comments;


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setArticle($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getArticle() === $this) {
                $image->setArticle(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPublishAt(): ?\DateTimeInterface
    {
        return $this->publish_at;
    }

    public function setPublishAt(\DateTimeInterface $publish_at): self
    {
        $this->publish_at = $publish_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }
    public function getPub()
    {
        # code...
    }
    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

   public function d()
   {
       $time= $this->publish_at;
      return $time->getTimestamp();
   }

}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Form\ImageType;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content',CKEditorType::class)
            ->add('photos',FileType::class,[
                'attr'=>[
                    'accept'=>'image/png, image/jpg, image/jpeg, image/gif'
                ],
                'mapped'=>false,
                'multiple'=>true,
            ])
            ->add('submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Entity\Article;
use App\Entity\Comment;
use App\Form\ArticleType;
use App\Form\CommentType;
use App\Repository\ArticleRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/articles")
 */
class ArticlesController extends AbstractController
{
    /**
     * @Route("/view/{id}.html", name="view")
     */
    public function view(Article $article=null,Request $r)
    {
        $comment= new Comment();
        $form= $this->createForm(CommentType::class,$comment);
        $form->handleRequest($r);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setArticle($article);
            $comment->setPublishAt(new \Datetime());
            $m= $this->getDoctrine()->getManager();
            $m->persist($comment);
            $m->flush();

        }
        return $this->render('articles/view.html.twig', [
            'article' => $article,
            'form'=> $form->createView(),
        ]);
    }
    /**
     * @Route("/", name="articles")
     */
    public function index(ArticleRepository $ar)
    {
        $articles= $ar->findAll();
        return $this->render('articles/home.html.twig', [
            'articles' => $articles,
        ]);
    }
     /**
     * @Route("/edit/{id}", name="articles_edit")
     */
    public function edit(Article $article=null,Request $req)
    {
        $form= $this->createForm(ArticleType::class,$article);
        $form->handleRequest($req);
        if ($form->isSubmitted() && $form->isValid()) {
            $em= $this->getDoctrine()->getManager();
            $article->setUpdateAt(new \Datetime());
            $em->persist($article);
            $em->flush();
            $photos= $form->get('photos')->getData();
            foreach ($photos as  $value) {
                $img= ['png','jpg','jpeg','gif','JPJ','JPEG','PNG','GIF'];
                $ext=$value->guessExtension();
                $name=$value->getClientOriginalName();
                
                if ( in_array($ext,$img) ) {
                    $image= new Image();
                    $image->setChemin('img/'.$name);
                    $m=$this->getDoctrine()->getManager();
                    $m->persist($image);
                    $m->flush();
                    $article->addImage($image);
                    $value->move('img',$name);
                    
                }
            } 
            $em->flush();
        }

        return $this->render('articles/edite.html.twig', [
            'form' => $form->createView(),
            'images'=>$article->getImages(),
        ]);
    }
    /**
     * @Route("/new", name="articles_new")
     */
    public function new(Request $r)
    {
        $article = new Article();
        $form= $this->createForm(ArticleType::class,$article);
        $form->handleRequest($r);
        if ($form->isSubmitted() && $form->isValid()) {
            $em= $this->getDoctrine()->getManager();
            $article->setPublishAt(new \Datetime());
            $article->setUpdateAt(new \Datetime());
            $em->persist($article);
            $em->flush();
            $photos= $form->get('photos')->getData();
            foreach ($photos as  $value) {
                $img= ['png','jpg','jpeg','gif','JPJ','JPEG','PNG','GIF'];
                $ext=$value->guessExtension();
                $name=$value->getClientOriginalName();
                
                if ( in_array($ext,$img) ) {
                    $image= new Image();
                    $image->setChemin('img/'.$name);
                    $m=$this->getDoctrine()->getManager();
                    $m->persist($image);
                    $m->flush();
                    $article->addImage($image);
                    $value->move('img',$name);
                }
            } 
            $em->flush();
            return $this->redirectToRoute('articles_edit',['id'=>$article->getId()]);
        }
        return $this->render('articles/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }
     /**
     * @Route("-read-{id}.html", name="articles_read")
     */
    public function read(Article $ar=null)
    {
        return $this->render('articles/read.html.twig', [
            'article' => $ar,
        ]);
    }
}

templates/articles/edite.html.twig
{% extends "base.html.twig" %}
{% block body %}
    {{ form(form )}}
    {% for im in images %}
        <img width='350px' heigth='300px' src='{{ asset(im.chemin) }}'/>
    {% endfor %}
{% endblock %}

templates/articles/home.html.twig
{% extends "base.html.twig" %}
{% block body %}
<div class="row">
    {% for article in articles %}
      <div class="col-sm-12 card article-card col-lg-6">
        <h3 class='card-title'><b>{{ article.title | upper}}</b></h3>
        <h6>{{ article.publishAt |date }}</h6>
        <div class='row'>
          {% for image in article.images %}
            <div class='col'>
              <img class='img-fluid' src='{{ asset(image.chemin) }}'/>
            </div>
          {% endfor %}
        </div>
         <div>{{article.content | raw }}</div>
         <!-- Facebook -->
    <a type="button" class="btn-floating btn-small"><i class="fab fa-facebook-f"></i></a>
         <a class='btn btn-primary' href="{{ path('articles_read',{'id':article.id})}}">Voire plus</a>
        {% if app.user %}
            <button >Spprimer</button><button >editer</button>
        {% endif %}
      </div>
    {% endfor %}
</div>
{% endblock %}

{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/locale/fr-ca.min.js" integrity="sha512-6ftq6p0da6fhwkJeaW+hDKAxinsJm819v2Q4c8to1i+s2unTT6pqnDP3YN2BHGc6ENSgKirV1d/nI71XEsZH0g==" crossorigin="anonymous"></script>
{% endblock %}

templates/articles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticlesController!{% endblock %}

{% block body %}
{{form(form)}}
{% endblock %}

templates/articles/read.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
             <h2 class="text-center">{{ article.title | upper }}</h2>
        </div>
        <div class="col-sm-12 row">
            {% for image in article.images %}
            <div class="col card">
                <div class='card-image'>
                    <img class='img-fluid' src='{{ asset(image.chemin) }}'/>
                </div>
            </div>
           
          {% endfor %}
        </div>
        <div class="col-sm-12 card">
          {{ article.content | raw }}
        </div>
    </div>
{% endblock %}

templates/articles/view.html.twig
{% extends "base.html.twig" %}
{% block body %}
     <p>
        <div> <b>{{ article.title }}</b> </div>
        <div> publishat {{ article.publishAt | date }}</div>
        <div>{{article.content}}</div>
        {% for image in article.images %}
            <img width='200px' height='150px'src='{{ asset(image.chemin) }}'/>
        {% endfor %}
        <br>
        <button >Partager</button>
    </p>
    {% for comment in article.comments  %}
        <div> {{ comment.comment }}</div>    
    {% endfor %}
    {{ form(form) }}
{% endblock %}